#*******************************************************************************
#* makefile.mk
#*------------------------------------------------------------------------------
#* Makefile used to generate the Application DLL (GNU WIN32 format).
#* This file was automatically generated by IngeDev. Please, do not edit!
#*******************************************************************************

#-------------------------------------------------------------------------------
# General constants
#-------------------------------------------------------------------------------
EMPTY :=
SPACE := $(EMPTY) $(EMPTY)

#-------------------------------------------------------------------------------
# Project and file names
#-------------------------------------------------------------------------------
# Project name
PROJECT_NAME    := ISOZZSG_TELIUM
# Compiler version
COMPILER_VERSION	:= GNU WIN32
# Configuration name
CFG_NAME        := SIMULATION
# Target file name (without extension)
TRG_FILE_NAME   := ISOZZSG


#-------------------------------------------------------------------------------
# Directories
#-------------------------------------------------------------------------------
# Binaries directory
BIN_DIR         := Bin
# Object directory
OBJ_DIR         := Obj
# Build files directory
BUILD_FILES_DIR := BuildFiles

#-------------------------------------------------------------------------------
# VisualC object file to be included during link operation 
#-------------------------------------------------------------------------------
# VisualC object file to allow linking with VisualC library
VISUALC_OBJ_FILE = C:/Program\ Files/Ingenico/IngeDev_7/plugins/com.ingenico.ingedev.telium.simulation.bin.win32_7.5.0.6/simulation/obj/chkstk.o

#-------------------------------------------------------------------------------
# Input files path for the current configuration
#-------------------------------------------------------------------------------
# Build files path
BUILD_FILES_PATH:= $(BUILD_FILES_DIR)/$(CFG_NAME)

#-------------------------------------------------------------------------------
# Output files path for the current configuration
#-------------------------------------------------------------------------------
# Object files path
OBJ_PATH        := $(OBJ_DIR)/$(CFG_NAME)
# Binary files path
BIN_PATH        := $(BIN_DIR)/$(CFG_NAME)

#-------------------------------------------------------------------------------
# Compiler, linker, assembler, ...
#-------------------------------------------------------------------------------
# Gnu Win32 Compiler executable
CC              := gcc.exe
# Gnu Win32 Assembler executable
AS              := as.exe
# Gnu Win32 Strip debug symbol executable
STRIP           := strip.exe -g

#-------------------------------------------------------------------------------
# Gnu Win32 tools
#-------------------------------------------------------------------------------
# Remove tool
RM              := rm.exe -fr
# Make directory tool
MKDIR           := mkdir.exe -p
# Copy tool
CP              := cp.exe
# Printf tool
PRINTF          := printf.exe

#-------------------------------------------------------------------------------
# Includes path used in compilation process
#-------------------------------------------------------------------------------
INCLUDES_PATH   := \
-I"Inc" \
-I"P:/work/regional/application/UtaTemplate/uta100407/sys" \
-I"P:/work/regional/application/UtaTemplate/uta100407/pri" \
-I"uta" \
-I"P:/work/regional/application/UtaTemplate/ZZ/ISOZZSG/str" \
-I"P:/work/regional/application/UtaTemplate/ZZ/ISOZZSG/log" \
-I"P:/work/regional/application/UtaTemplate/ZZ/ISOZZSG/tst" \
-I"C:/Program Files/SDK30/SDK 7.4/SDK/inc" \

#-------------------------------------------------------------------------------
# Libraries to be included during link operation
#-------------------------------------------------------------------------------
LIBS            := \
C:/Program\ Files/SDK30/SDK\ 7.4/SDK/lib_simul/eft30.lib \
C:/Program\ Files/SDK30/SDK\ 7.4/SDK/lib_simul/IAPP.lib \
C:/Program\ Files/SDK30/SDK\ 7.4/SDK/lib_simul/AVL.lib \
C:/Program\ Files/SDK30/SDK\ 7.4/SDK/lib_simul/LinkLayerExeInterface.lib \

LIBS            += \
C:/Program\ Files/Ingenico/IngeDev_7/plugins/com.ingenico.ingedev.telium.simulation.bin.win32_7.5.0.6/simulation/lib/SimuConnect.lib \
C:/Program\ Files/Ingenico/IngeDev_7/plugins/com.ingenico.ingedev.telium.simulation.bin.win32_7.5.0.6/simulation/lib/SimuDLLInterface.lib

#-------------------------------------------------------------------------------
# System libraries to be included during link operation
#-------------------------------------------------------------------------------
SYSTEM_LIBS     := \
-L C:/Program\ Files/Ingenico/IngeDev_7/plugins/com.ingenico.ingedev.generic.bin.win32_7.5.0.6/os/win32/GNUWIN32/lib -lsupc++

#-------------------------------------------------------------------------------
# Result output files
#-------------------------------------------------------------------------------
# DLL file
DLL_FILE        := $(BIN_PATH)/$(TRG_FILE_NAME).dll

#-------------------------------------------------------------------------------
# Default compiler, linker, assembler options
#-------------------------------------------------------------------------------
# Default compiler options
CC_DEF_OPTS     := -ggdb3 -gdwarf-2 -c -fsigned-char -Wunused-variable
# Default assembler options
AS_DEF_OPTS     := --gdwarf2
# Default compiler options for link process
CC_LD_DEF_OPTS  := -shared -d C:/Program\ Files/Ingenico/IngeDev_7/plugins/com.ingenico.ingedev.telium.simulation.bin.win32_7.5.0.6/simulation/def/SimuDllExports.def

#-------------------------------------------------------------------------------
# Specific compiler, linker, assembler options
#-------------------------------------------------------------------------------
# Specific compiler options
CC_SPEC_OPTS    := -fno-exceptions  -D_ING_SIMULATION
CC_SPEC_OPTS    +=  -D_EXPORT_ -D_EFT30_ -D_SIMULPC_
CC_SPEC_OPTS    +=  -D__ISOZZSG__ -D__TELIUM__ -D_ING_APPLI_BINARY_NAME=\"ISOZZSG\" -D_ING_APPLI_FAMILY=\"ISOZZSG\" -D_ING_APPLI_TYPE=0x6e -D_ING_APPLI_CURRENT_CONFIG_NAME=\"SIMULATION\" -D_ING_APPLI_FULL_BINARY_NAME=\"ISOZZSG.SGN\" -D_ING_APPLI_TELIUM1_FULL_BINARY_NAME=\"ISOZZSG.SGN\" -D_ING_APPLI_TELIUM2_FULL_BINARY_NAME=\"ISOZZSG.AGN\" -D_ING_APPLI_TELIUM_COMPATIBILITY=\"Telium_1\" -D_ING_APPLI_SIGN_MODE=\"Unsigned\" -D_ING_APPLI_CATALOG_FILE_EXTENSION=\"M3X\" -D_ING_APPLI_CURRENT_CONFIG_TOOLCHAIN_ROOT_LOCATION=\"C:/Program\ Files/Ingenico/IngeDev_7/plugins/com.ingenico.ingedev.generic.bin.win32_7.5.0.6/os/win32/GNUWIN32\" $(INCLUDES_PATH)
# Specific assembler options
AS_SPEC_OPTS    :=   --defsym _ING_SIMULATION=1
AS_SPEC_OPTS    +=  --defsym _EXPORT_=1 --defsym _EFT30_=1 --defsym _SIMULPC_=1
AS_SPEC_OPTS    +=  --defsym __ISOZZSG__=1 --defsym __TELIUM__=1 --defsym _ING_APPLI_BINARY_NAME=\"ISOZZSG\" --defsym _ING_APPLI_FAMILY=\"ISOZZSG\" --defsym _ING_APPLI_TYPE=0x6e --defsym _ING_APPLI_CURRENT_CONFIG_NAME=\"SIMULATION\" --defsym _ING_APPLI_FULL_BINARY_NAME=\"ISOZZSG.SGN\" --defsym _ING_APPLI_TELIUM1_FULL_BINARY_NAME=\"ISOZZSG.SGN\" --defsym _ING_APPLI_TELIUM2_FULL_BINARY_NAME=\"ISOZZSG.AGN\" --defsym _ING_APPLI_TELIUM_COMPATIBILITY=\"Telium_1\" --defsym _ING_APPLI_SIGN_MODE=\"Unsigned\" --defsym _ING_APPLI_CATALOG_FILE_EXTENSION=\"M3X\" --defsym _ING_APPLI_CURRENT_CONFIG_TOOLCHAIN_ROOT_LOCATION=\"C:/Program\ Files/Ingenico/IngeDev_7/plugins/com.ingenico.ingedev.generic.bin.win32_7.5.0.6/os/win32/GNUWIN32\" $(INCLUDES_PATH)
# Specific compiler options for link process
CC_LD_SPEC_OPTS := 

#-------------------------------------------------------------------------------
# Compiler, linker, assembler options
# default + specific options
#-------------------------------------------------------------------------------
# Compiler options
CC_OPTS         := $(CC_DEF_OPTS) $(CC_SPEC_OPTS)
# Assembler options
AS_OPTS         := $(AS_DEF_OPTS) $(AS_SPEC_OPTS)
# Compiler options for link process
CC_LD_OPTS      := $(CC_LD_DEF_OPTS) $(CC_LD_SPEC_OPTS)

#-------------------------------------------------------------------------------
# SRC_OBJS is the list of the project object files
#-------------------------------------------------------------------------------
SRC_OBJS        := \
$(OBJ_PATH)/trc.o \
$(OBJ_PATH)/tbx.o \
$(OBJ_PATH)/tlm.o \
$(OBJ_PATH)/tlmhmi.o \
$(OBJ_PATH)/tlmmem.o \
$(OBJ_PATH)/std.o \
$(OBJ_PATH)/fmt.o \
$(OBJ_PATH)/dba.o \
$(OBJ_PATH)/drv.o \
$(OBJ_PATH)/dlg.o \
$(OBJ_PATH)/Main.o \
$(OBJ_PATH)/sgm.o \
$(OBJ_PATH)/map.o \
$(OBJ_PATH)/dft.o \
$(OBJ_PATH)/rpt.o \
$(OBJ_PATH)/scr.o \
$(OBJ_PATH)/str.o \
$(OBJ_PATH)/hdl.o \
$(OBJ_PATH)/val.o \
$(OBJ_PATH)/adm.o \
$(OBJ_PATH)/emv.o \
$(OBJ_PATH)/EmvMultiCurr.o \
$(OBJ_PATH)/function.o \
$(OBJ_PATH)/iso.o \
$(OBJ_PATH)/log.o \
$(OBJ_PATH)/onl.o \
$(OBJ_PATH)/pmt.o \
$(OBJ_PATH)/req.o \
$(OBJ_PATH)/rev.o \
$(OBJ_PATH)/rsp.o \
$(OBJ_PATH)/tle.o \
$(OBJ_PATH)/cmm.o \
$(OBJ_PATH)/tlmchn.o \
$(OBJ_PATH)/tlmcry.o \
$(OBJ_PATH)/tlmemv.o \
$(OBJ_PATH)/tcan0020.o \

#-------------------------------------------------------------------------------
# Dependencies
#-------------------------------------------------------------------------------
DEPENDENCIES    := \
$(BUILD_FILES_PATH)/makefile.mk

#===============================================================================
# Rule to make the project
#===============================================================================
#-------------------------------------------------------------------------------
# Rule for the DLL file generation
#-------------------------------------------------------------------------------
$(DLL_FILE): $(SRC_OBJS) $(LIBS)
	@$(PRINTF) "'$@' link in progress...\n"
	$(CC) $(CC_LD_OPTS) -o $@ $(SRC_OBJS) -Wl,-\( $(LIBS) -Wl,-\) $(SYSTEM_LIBS) $(VISUALC_OBJ_FILE)
ifeq "$(REMOVE_SYMBOLS)" "true"
	@$(PRINTF) "'$@' strip debug symbols in progress...\n"
	$(STRIP) $@ -o $(dir $@)/_$(notdir $@)
endif
	@$(PRINTF) "'$@' Win32 dll file generated.\n"

#===============================================================================
# Rule for the compilation process
#===============================================================================
ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/trc.d
endif
$(OBJ_PATH)/trc.o: P:/work/regional/application/UtaTemplate/uta100407/sys/trc.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@$(PRINTF) "'P:/work/regional/application/UtaTemplate/uta100407/sys/trc.c' compilation in progress...\n"
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/trc.o)
	@$(PRINTF) "done!\n"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/tbx.d
endif
$(OBJ_PATH)/tbx.o: P:/work/regional/application/UtaTemplate/uta100407/sys/tbx.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@$(PRINTF) "'P:/work/regional/application/UtaTemplate/uta100407/sys/tbx.c' compilation in progress...\n"
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/tbx.o)
	@$(PRINTF) "done!\n"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/tlm.d
endif
$(OBJ_PATH)/tlm.o: P:/work/regional/application/UtaTemplate/uta100407/sys/tlm.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@$(PRINTF) "'P:/work/regional/application/UtaTemplate/uta100407/sys/tlm.c' compilation in progress...\n"
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/tlm.o)
	@$(PRINTF) "done!\n"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/tlmhmi.d
endif
$(OBJ_PATH)/tlmhmi.o: P:/work/regional/application/UtaTemplate/uta100407/sys/tlmhmi.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@$(PRINTF) "'P:/work/regional/application/UtaTemplate/uta100407/sys/tlmhmi.c' compilation in progress...\n"
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/tlmhmi.o)
	@$(PRINTF) "done!\n"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/tlmmem.d
endif
$(OBJ_PATH)/tlmmem.o: P:/work/regional/application/UtaTemplate/uta100407/sys/tlmmem.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@$(PRINTF) "'P:/work/regional/application/UtaTemplate/uta100407/sys/tlmmem.c' compilation in progress...\n"
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/tlmmem.o)
	@$(PRINTF) "done!\n"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/std.d
endif
$(OBJ_PATH)/std.o: P:/work/regional/application/UtaTemplate/uta100407/pri/std.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@$(PRINTF) "'P:/work/regional/application/UtaTemplate/uta100407/pri/std.c' compilation in progress...\n"
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/std.o)
	@$(PRINTF) "done!\n"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/fmt.d
endif
$(OBJ_PATH)/fmt.o: P:/work/regional/application/UtaTemplate/uta100407/pri/fmt.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@$(PRINTF) "'P:/work/regional/application/UtaTemplate/uta100407/pri/fmt.c' compilation in progress...\n"
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/fmt.o)
	@$(PRINTF) "done!\n"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/dba.d
endif
$(OBJ_PATH)/dba.o: P:/work/regional/application/UtaTemplate/uta100407/pri/dba.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@$(PRINTF) "'P:/work/regional/application/UtaTemplate/uta100407/pri/dba.c' compilation in progress...\n"
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/dba.o)
	@$(PRINTF) "done!\n"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/drv.d
endif
$(OBJ_PATH)/drv.o: P:/work/regional/application/UtaTemplate/uta100407/pri/drv.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@$(PRINTF) "'P:/work/regional/application/UtaTemplate/uta100407/pri/drv.c' compilation in progress...\n"
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/drv.o)
	@$(PRINTF) "done!\n"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/dlg.d
endif
$(OBJ_PATH)/dlg.o: P:/work/regional/application/UtaTemplate/uta100407/pri/dlg.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@$(PRINTF) "'P:/work/regional/application/UtaTemplate/uta100407/pri/dlg.c' compilation in progress...\n"
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/dlg.o)
	@$(PRINTF) "done!\n"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/Main.d
endif
$(OBJ_PATH)/Main.o: uta/Main.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@$(PRINTF) "'uta/Main.c' compilation in progress...\n"
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/Main.o)
	@$(PRINTF) "done!\n"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/sgm.d
endif
$(OBJ_PATH)/sgm.o: uta/sgm.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@$(PRINTF) "'uta/sgm.c' compilation in progress...\n"
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/sgm.o)
	@$(PRINTF) "done!\n"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/map.d
endif
$(OBJ_PATH)/map.o: P:/work/regional/application/UtaTemplate/ZZ/ISOZZSG/str/map.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@$(PRINTF) "'P:/work/regional/application/UtaTemplate/ZZ/ISOZZSG/str/map.c' compilation in progress...\n"
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/map.o)
	@$(PRINTF) "done!\n"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/dft.d
endif
$(OBJ_PATH)/dft.o: P:/work/regional/application/UtaTemplate/ZZ/ISOZZSG/str/dft.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@$(PRINTF) "'P:/work/regional/application/UtaTemplate/ZZ/ISOZZSG/str/dft.c' compilation in progress...\n"
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/dft.o)
	@$(PRINTF) "done!\n"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/rpt.d
endif
$(OBJ_PATH)/rpt.o: P:/work/regional/application/UtaTemplate/ZZ/ISOZZSG/str/rpt.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@$(PRINTF) "'P:/work/regional/application/UtaTemplate/ZZ/ISOZZSG/str/rpt.c' compilation in progress...\n"
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/rpt.o)
	@$(PRINTF) "done!\n"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/scr.d
endif
$(OBJ_PATH)/scr.o: P:/work/regional/application/UtaTemplate/ZZ/ISOZZSG/str/scr.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@$(PRINTF) "'P:/work/regional/application/UtaTemplate/ZZ/ISOZZSG/str/scr.c' compilation in progress...\n"
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/scr.o)
	@$(PRINTF) "done!\n"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/str.d
endif
$(OBJ_PATH)/str.o: P:/work/regional/application/UtaTemplate/ZZ/ISOZZSG/str/str.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@$(PRINTF) "'P:/work/regional/application/UtaTemplate/ZZ/ISOZZSG/str/str.c' compilation in progress...\n"
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/str.o)
	@$(PRINTF) "done!\n"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/hdl.d
endif
$(OBJ_PATH)/hdl.o: P:/work/regional/application/UtaTemplate/ZZ/ISOZZSG/log/hdl.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@$(PRINTF) "'P:/work/regional/application/UtaTemplate/ZZ/ISOZZSG/log/hdl.c' compilation in progress...\n"
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/hdl.o)
	@$(PRINTF) "done!\n"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/val.d
endif
$(OBJ_PATH)/val.o: P:/work/regional/application/UtaTemplate/ZZ/ISOZZSG/log/val.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@$(PRINTF) "'P:/work/regional/application/UtaTemplate/ZZ/ISOZZSG/log/val.c' compilation in progress...\n"
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/val.o)
	@$(PRINTF) "done!\n"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/adm.d
endif
$(OBJ_PATH)/adm.o: P:/work/regional/application/UtaTemplate/ZZ/ISOZZSG/log/adm.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@$(PRINTF) "'P:/work/regional/application/UtaTemplate/ZZ/ISOZZSG/log/adm.c' compilation in progress...\n"
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/adm.o)
	@$(PRINTF) "done!\n"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/emv.d
endif
$(OBJ_PATH)/emv.o: P:/work/regional/application/UtaTemplate/ZZ/ISOZZSG/log/emv.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@$(PRINTF) "'P:/work/regional/application/UtaTemplate/ZZ/ISOZZSG/log/emv.c' compilation in progress...\n"
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/emv.o)
	@$(PRINTF) "done!\n"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/EmvMultiCurr.d
endif
$(OBJ_PATH)/EmvMultiCurr.o: P:/work/regional/application/UtaTemplate/ZZ/ISOZZSG/log/EmvMultiCurr.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@$(PRINTF) "'P:/work/regional/application/UtaTemplate/ZZ/ISOZZSG/log/EmvMultiCurr.c' compilation in progress...\n"
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/EmvMultiCurr.o)
	@$(PRINTF) "done!\n"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/function.d
endif
$(OBJ_PATH)/function.o: P:/work/regional/application/UtaTemplate/ZZ/ISOZZSG/log/function.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@$(PRINTF) "'P:/work/regional/application/UtaTemplate/ZZ/ISOZZSG/log/function.c' compilation in progress...\n"
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/function.o)
	@$(PRINTF) "done!\n"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/iso.d
endif
$(OBJ_PATH)/iso.o: P:/work/regional/application/UtaTemplate/ZZ/ISOZZSG/log/iso.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@$(PRINTF) "'P:/work/regional/application/UtaTemplate/ZZ/ISOZZSG/log/iso.c' compilation in progress...\n"
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/iso.o)
	@$(PRINTF) "done!\n"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/log.d
endif
$(OBJ_PATH)/log.o: P:/work/regional/application/UtaTemplate/ZZ/ISOZZSG/log/log.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@$(PRINTF) "'P:/work/regional/application/UtaTemplate/ZZ/ISOZZSG/log/log.c' compilation in progress...\n"
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/log.o)
	@$(PRINTF) "done!\n"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/onl.d
endif
$(OBJ_PATH)/onl.o: P:/work/regional/application/UtaTemplate/ZZ/ISOZZSG/log/onl.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@$(PRINTF) "'P:/work/regional/application/UtaTemplate/ZZ/ISOZZSG/log/onl.c' compilation in progress...\n"
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/onl.o)
	@$(PRINTF) "done!\n"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/pmt.d
endif
$(OBJ_PATH)/pmt.o: P:/work/regional/application/UtaTemplate/ZZ/ISOZZSG/log/pmt.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@$(PRINTF) "'P:/work/regional/application/UtaTemplate/ZZ/ISOZZSG/log/pmt.c' compilation in progress...\n"
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/pmt.o)
	@$(PRINTF) "done!\n"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/req.d
endif
$(OBJ_PATH)/req.o: P:/work/regional/application/UtaTemplate/ZZ/ISOZZSG/log/req.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@$(PRINTF) "'P:/work/regional/application/UtaTemplate/ZZ/ISOZZSG/log/req.c' compilation in progress...\n"
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/req.o)
	@$(PRINTF) "done!\n"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/rev.d
endif
$(OBJ_PATH)/rev.o: P:/work/regional/application/UtaTemplate/ZZ/ISOZZSG/log/rev.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@$(PRINTF) "'P:/work/regional/application/UtaTemplate/ZZ/ISOZZSG/log/rev.c' compilation in progress...\n"
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/rev.o)
	@$(PRINTF) "done!\n"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/rsp.d
endif
$(OBJ_PATH)/rsp.o: P:/work/regional/application/UtaTemplate/ZZ/ISOZZSG/log/rsp.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@$(PRINTF) "'P:/work/regional/application/UtaTemplate/ZZ/ISOZZSG/log/rsp.c' compilation in progress...\n"
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/rsp.o)
	@$(PRINTF) "done!\n"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/tle.d
endif
$(OBJ_PATH)/tle.o: P:/work/regional/application/UtaTemplate/ZZ/ISOZZSG/log/tle.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@$(PRINTF) "'P:/work/regional/application/UtaTemplate/ZZ/ISOZZSG/log/tle.c' compilation in progress...\n"
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/tle.o)
	@$(PRINTF) "done!\n"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/cmm.d
endif
$(OBJ_PATH)/cmm.o: P:/work/regional/application/UtaTemplate/uta100407/sys/cmm.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@$(PRINTF) "'P:/work/regional/application/UtaTemplate/uta100407/sys/cmm.c' compilation in progress...\n"
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/cmm.o)
	@$(PRINTF) "done!\n"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/tlmchn.d
endif
$(OBJ_PATH)/tlmchn.o: P:/work/regional/application/UtaTemplate/uta100407/sys/tlmchn.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@$(PRINTF) "'P:/work/regional/application/UtaTemplate/uta100407/sys/tlmchn.c' compilation in progress...\n"
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/tlmchn.o)
	@$(PRINTF) "done!\n"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/tlmcry.d
endif
$(OBJ_PATH)/tlmcry.o: P:/work/regional/application/UtaTemplate/uta100407/sys/tlmcry.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@$(PRINTF) "'P:/work/regional/application/UtaTemplate/uta100407/sys/tlmcry.c' compilation in progress...\n"
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/tlmcry.o)
	@$(PRINTF) "done!\n"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/tlmemv.d
endif
$(OBJ_PATH)/tlmemv.o: P:/work/regional/application/UtaTemplate/uta100407/sys/tlmemv.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@$(PRINTF) "'P:/work/regional/application/UtaTemplate/uta100407/sys/tlmemv.c' compilation in progress...\n"
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/tlmemv.o)
	@$(PRINTF) "done!\n"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/tcan0020.d
endif
$(OBJ_PATH)/tcan0020.o: P:/work/regional/application/UtaTemplate/uta100407/tst/an/tcan0020.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@$(PRINTF) "'P:/work/regional/application/UtaTemplate/uta100407/tst/an/tcan0020.c' compilation in progress...\n"
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/tcan0020.o)
	@$(PRINTF) "done!\n"
endif

#===============================================================================
# Rule for project name and configuration name display
#===============================================================================
.PHONY: displayInfo
displayInfo:
	@$(PRINTF) "                                     *-*-*\n"
	@$(PRINTF) "--- Project '$(PROJECT_NAME)', Configuration '$(CFG_NAME)', Compiler '$(COMPILER_VERSION)' ---\n"

#===============================================================================
# Rule for output directories creation
#===============================================================================
.PHONY: createOutputDirs
createOutputDirs:
	@$(MKDIR) "$(OBJ_PATH)"
	@$(MKDIR) "$(BIN_PATH)"

#===============================================================================
# Make build rule
#===============================================================================
.PHONY: build
build: displayInfo createOutputDirs $(DLL_FILE)
	@$(PRINTF) "done!\n"

#===============================================================================
# Make clean rule
#===============================================================================
.PHONY: clean
clean: displayInfo
	@$(PRINTF) "deleting intermediate files...\n"
	@$(RM) "$(DLL_FILE)"
ifneq "$(wildcard $(OBJ_PATH)/*.*)" ""
	@$(RM) "$(OBJ_PATH)/*.*"
endif
	@$(PRINTF) "done!\n"
