<?xml version="1.0"?>

<xsl:transform version = "1.0" id="xml2fnt"
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
>

<xsl:output method="text"/>
<xsl:strip-space elements="*"/>

<xsl:template match="/">
    <xsl:text>//Generated by xml2fnt.xsl from ttf,bdf and xml &#010;</xsl:text>
    <xsl:text>&#010;</xsl:text>
    <xsl:apply-templates/>
    <xsl:text>&#010;</xsl:text>
</xsl:template>

<xsl:template match="BDFFONT">
    <xsl:apply-templates/>
    <xsl:text>&#010;</xsl:text>
        <xsl:text>static const unsigned char *gly[]={&#010;</xsl:text>
    <xsl:apply-templates mode="array"/>
    <xsl:text>    0&#010;</xsl:text>
    <xsl:text>};&#010;</xsl:text>
    <xsl:text>&#010;</xsl:text>
</xsl:template>

<xsl:template match="CHAR">
    <xsl:if test="count(BITMAP/BMPLINE)!=0">
        <xsl:text>static const unsigned char gly</xsl:text>
        <xsl:value-of select="@glyphname"/>
        <xsl:text>[]= { &#010;</xsl:text>
        <xsl:apply-templates/>
        <xsl:text>};&#010;</xsl:text>
    </xsl:if>
</xsl:template>

<xsl:template match="BOX"><xsl:apply-templates/></xsl:template>

<xsl:template match="BOXLINE">
    <xsl:text>    </xsl:text>
    <xsl:if test="substring(@hex,1,2)!=''">
        <xsl:text>0x</xsl:text>
        <xsl:value-of select="substring(@hex,1,2)"/>
        <xsl:text>,</xsl:text>
    </xsl:if>
    <xsl:if test="substring(@hex,3,2)!=''">
        <xsl:text>0x</xsl:text>
        <xsl:value-of select="substring(@hex,3,2)"/>
        <xsl:text>,</xsl:text>
    </xsl:if>
    <xsl:if test="substring(@hex,5,2)!=''">
        <xsl:text>0x</xsl:text>
        <xsl:value-of select="substring(@hex,5,2)"/>
        <xsl:text>,</xsl:text>
    </xsl:if>
    <xsl:if test="substring(@hex,7,2)!=''">
        <xsl:text>0x</xsl:text>
        <xsl:value-of select="substring(@hex,7,2)"/>
        <xsl:text>,</xsl:text>
    </xsl:if>
    <xsl:if test="substring(@hex,9,2)!=''">
        <xsl:text>0x</xsl:text>
        <xsl:value-of select="substring(@hex,9,2)"/>
        <xsl:text>,</xsl:text>
    </xsl:if>
    <xsl:if test="substring(@hex,11,2)!=''">
        <xsl:text>0x</xsl:text>
        <xsl:value-of select="substring(@hex,11,2)"/>
        <xsl:text>,</xsl:text>
    </xsl:if>
    <xsl:if test="substring(@hex,13,2)!=''">
        <xsl:text>0x</xsl:text>
        <xsl:value-of select="substring(@hex,13,2)"/>
        <xsl:text>,</xsl:text>
    </xsl:if>
    <xsl:if test="substring(@hex,15,2)!=''">
        <xsl:text>0x</xsl:text>
        <xsl:value-of select="substring(@hex,15,2)"/>
        <xsl:text>,</xsl:text>
    </xsl:if>
    <xsl:if test="substring(@hex,17,2)!=''">
        <xsl:text>0x</xsl:text>
        <xsl:value-of select="substring(@hex,17,2)"/>
        <xsl:text>,</xsl:text>
    </xsl:if>
    <xsl:if test="substring(@hex,19,2)!=''">
        <xsl:text>0x</xsl:text>
        <xsl:value-of select="substring(@hex,19,2)"/>
        <xsl:text>,</xsl:text>
    </xsl:if>
    <xsl:if test="substring(@hex,21,2)!=''">
        <xsl:text>0x</xsl:text>
        <xsl:value-of select="substring(@hex,21,2)"/>
        <xsl:text>,</xsl:text>
    </xsl:if>
    <xsl:if test="substring(@hex,23,2)!=''">
        <xsl:text>0x</xsl:text>
        <xsl:value-of select="substring(@hex,23,2)"/>
        <xsl:text>,</xsl:text>
    </xsl:if>
    <xsl:if test="substring(@hex,25,2)!=''">
        <xsl:text>0x</xsl:text>
        <xsl:value-of select="substring(@hex,25,2)"/>
        <xsl:text>,</xsl:text>
    </xsl:if>
    <xsl:if test="substring(@hex,27,2)!=''">
        <xsl:text>0x</xsl:text>
        <xsl:value-of select="substring(@hex,27,2)"/>
        <xsl:text>,</xsl:text>
    </xsl:if>
    <xsl:if test="substring(@hex,29,2)!=''">
        <xsl:text>0x</xsl:text>
        <xsl:value-of select="substring(@hex,29,2)"/>
        <xsl:text>,</xsl:text>
    </xsl:if>
    <xsl:if test="substring(@hex,31,2)!=''">
        <xsl:text>0x</xsl:text>
        <xsl:value-of select="substring(@hex,31,2)"/>
        <xsl:text>,</xsl:text>
    </xsl:if>
    <xsl:if test="substring(@hex,33,2)!=''">
        <xsl:text>0x</xsl:text>
        <xsl:value-of select="substring(@hex,33,2)"/>
        <xsl:text>,</xsl:text>
    </xsl:if>
    <xsl:if test="substring(@hex,35,2)!=''">
        <xsl:text>0x</xsl:text>
        <xsl:value-of select="substring(@hex,35,2)"/>
        <xsl:text>,</xsl:text>
    </xsl:if>
    <xsl:if test="substring(@hex,37,2)!=''">
        <xsl:text>0x</xsl:text>
        <xsl:value-of select="substring(@hex,37,2)"/>
        <xsl:text>,</xsl:text>
    </xsl:if>
    <xsl:if test="substring(@hex,39,2)!=''">
        <xsl:text>0x</xsl:text>
        <xsl:value-of select="substring(@hex,39,2)"/>
        <xsl:text>,</xsl:text>
    </xsl:if>
    <xsl:if test="substring(@hex,41,2)!=''">
        <xsl:text>0x</xsl:text>
        <xsl:value-of select="substring(@hex,41,2)"/>
        <xsl:text>,</xsl:text>
    </xsl:if>
    <xsl:if test="substring(@hex,43,2)!=''">
        <xsl:text>0x</xsl:text>
        <xsl:value-of select="substring(@hex,43,2)"/>
        <xsl:text>,</xsl:text>
    </xsl:if>
    <xsl:if test="substring(@hex,45,2)!=''">
        <xsl:text>0x</xsl:text>
        <xsl:value-of select="substring(@hex,45,2)"/>
        <xsl:text>,</xsl:text>
    </xsl:if>
    <xsl:if test="substring(@hex,47,2)!=''">
        <xsl:text>0x</xsl:text>
        <xsl:value-of select="substring(@hex,47,2)"/>
        <xsl:text>,</xsl:text>
    </xsl:if>
    <xsl:if test="substring(@hex,49,2)!=''">
        <xsl:text>0x</xsl:text>
        <xsl:value-of select="substring(@hex,49,2)"/>
        <xsl:text>,</xsl:text>
    </xsl:if>
    <xsl:if test="substring(@hex,51,2)!=''">
        <xsl:text>0x</xsl:text>
        <xsl:value-of select="substring(@hex,51,2)"/>
        <xsl:text>,</xsl:text>
    </xsl:if>
    <xsl:if test="substring(@hex,53,2)!=''">
        <xsl:text>0x</xsl:text>
        <xsl:value-of select="substring(@hex,53,2)"/>
        <xsl:text>,</xsl:text>
    </xsl:if>
    <xsl:if test="substring(@hex,55,2)!=''">
        <xsl:text>0x</xsl:text>
        <xsl:value-of select="substring(@hex,55,2)"/>
        <xsl:text>,</xsl:text>
    </xsl:if>
    <xsl:if test="substring(@hex,57,2)!=''">
        <xsl:text>0x</xsl:text>
        <xsl:value-of select="substring(@hex,57,2)"/>
        <xsl:text>,</xsl:text>
    </xsl:if>
    <xsl:if test="substring(@hex,59,2)!=''">
        <xsl:text>0x</xsl:text>
        <xsl:value-of select="substring(@hex,59,2)"/>
        <xsl:text>,</xsl:text>
    </xsl:if>
    <xsl:if test="substring(@hex,61,2)!=''">
        <xsl:text>0x</xsl:text>
        <xsl:value-of select="substring(@hex,61,2)"/>
        <xsl:text>,</xsl:text>
    </xsl:if>
    <xsl:if test="substring(@hex,63,2)!=''">
        <xsl:text>0x</xsl:text>
        <xsl:value-of select="substring(@hex,63,2)"/>
        <xsl:text>,</xsl:text>
    </xsl:if>
    <xsl:text> //</xsl:text>
    <xsl:value-of select="@bit"/>
    <xsl:text>&#010;</xsl:text>
</xsl:template>

<xsl:template match="CHAR" mode="array">
    <xsl:if test="count(BITMAP/BMPLINE)!=0">
        <xsl:text>    gly</xsl:text>
        <xsl:value-of select="@glyphname"/>
        <xsl:text>,&#010;</xsl:text>
    </xsl:if>
</xsl:template>

</xsl:transform>
