/*******************************************************************************
 * Message.h
 *------------------------------------------------------------------------------
 * This file was automatically generated by INGEDEV
 ******************************************************************************/
#ifndef MESSAGE_H_INCLUDED
#define MESSAGE_H_INCLUDED

#ifdef __cplusplus
extern "C"
{
#endif

	/**
	 * Treats a message received in the application's message queue.
	 * 
	 * @param msgReceived Pointer on message to treat
	 */
	void treatRecMsg(amgMsg_t *msg);

#ifdef __cplusplus
}
#endif

#endif
