#*******************************************************************************
#* makefile.mk
#*------------------------------------------------------------------------------
#* Makefile used to generate the Application binaries (ARM SDT format).
#* This file was automatically generated by IngeDev. Please, do not edit!
#*******************************************************************************

#-------------------------------------------------------------------------------
# General constants
#-------------------------------------------------------------------------------
EMPTY :=
SPACE := $(EMPTY) $(EMPTY)

#-------------------------------------------------------------------------------
# Project and file names
#-------------------------------------------------------------------------------
# Project name
PROJECT_NAME    := ISOZZSG_TELIUM
# Configuration name
CFG_NAME        := ARM_SDT_RELEASE
# Target file name (without extension)
TRG_FILE_NAME   := BRI
# Startup object file name
STARTUP_OBJ_NAME:= cstartup.o
# Mapping file name (RFU)
#MAPPING_DEF_NAME:= %MAPPING_DEF_NAME%


#-------------------------------------------------------------------------------
# Directories
#-------------------------------------------------------------------------------
# Binaries directory
BIN_DIR         := Bin
# Object directory
OBJ_DIR         := Obj
# Build files directory
BUILD_FILES_DIR := BuildFiles

#-------------------------------------------------------------------------------
# Input files path for the current configuration
#-------------------------------------------------------------------------------
# Build files path
BUILD_FILES_PATH:= $(BUILD_FILES_DIR)/$(CFG_NAME)

#-------------------------------------------------------------------------------
# Output files path for the current configuration
#-------------------------------------------------------------------------------
# Object files path
OBJ_PATH        := $(OBJ_DIR)/$(CFG_NAME)
# Binary files path
BIN_PATH        := $(BIN_DIR)/$(CFG_NAME)

#-------------------------------------------------------------------------------
# Compiler, linker, assembler
#-------------------------------------------------------------------------------
# Arm Compiler executable (thumb mode)
CC              := tcc.exe
# Arm Assembler executable (thumb mode)
AS              := tasm.exe
# Arm Linker executable
LD              := armlink.exe
# Arm binary file transforming executable
FROM_ELF        := fromelf.exe

#-------------------------------------------------------------------------------
# Gnu Win32 tools
#-------------------------------------------------------------------------------
# Remove tool
RM              := rm.exe -fr
# Make directory tool
MKDIR           := mkdir.exe -p
# Copy tool
CP              := cp.exe
# Printf tool
PRINTF          := printf.exe
# File string replacement tool (Global Search And Replace)
GSAR            := gsar.exe -o

#-------------------------------------------------------------------------------
# Includes path used in compilation process
#-------------------------------------------------------------------------------
INCLUDES_PATH   := \
-I"Inc" \
-I"uta" \
-I"D:/Documents and Settings/adr3an/IngeDev7_workspace/ISOZZSG/str" \
-I"D:/Documents and Settings/adr3an/IngeDev7_workspace/ISOZZSG/log" \
-I"D:/Documents and Settings/adr3an/IngeDev7_workspace/ISOZZSG/tst" \
-I"D:/Documents and Settings/adr3an/IngeDev7_workspace/uta100407/sys" \
-I"D:/Documents and Settings/adr3an/IngeDev7_workspace/uta100407/pri" \
-I"D:/Program Files/SDK30/SDK 7.5.1/SDK/inc" \

#-------------------------------------------------------------------------------
# Libraries to be included during link operation
#-------------------------------------------------------------------------------
LIBS            := \
libs/GNU_ARM_RELEASE/RSA.lib \
D:/Program\ Files/SDK30/SDK\ 7.5.1/SDK/lib_sdt/eft30.alf \
D:/Program\ Files/SDK30/SDK\ 7.5.1/SDK/lib_sdt/trap.alf \
D:/Program\ Files/SDK30/SDK\ 7.5.1/SDK/lib_sdt/PinLib.alf \
D:/Program\ Files/SDK30/SDK\ 7.5.1/SDK/lib_sdt/IAPP.lib \
D:/Program\ Files/SDK30/SDK\ 7.5.1/SDK/lib_sdt/AVL.lib \
D:/Program\ Files/SDK30/SDK\ 7.5.1/SDK/lib_sdt/LinkLayerExeInterface.lib \
D:/Program\ Files/SDK30/SDK\ 7.5.1/SDK/lib_sdt/SEC.lib \
D:/Program\ Files/SDK30/SDK\ 7.5.1/SDK/lib_sdt/dll_wifi.lib \
D:/Program\ Files/SDK30/SDK\ 7.5.1/SDK/lib_sdt/FTP_.lib \
D:/Program\ Files/SDK30/SDK\ 7.5.1/SDK/lib_sdt/SSL_.lib \
D:/Program\ Files/SDK30/SDK\ 7.5.1/SDK/lib_sdt/IP_.lib \
D:/Program\ Files/SDK30/SDK\ 7.5.1/SDK/lib_sdt/SNMP_.lib \
D:/Program\ Files/SDK30/SDK\ 7.5.1/SDK/lib_sdt/IMG_.lib \

#-------------------------------------------------------------------------------
# Compilation and link input files
#-------------------------------------------------------------------------------
# Mapping file location (used during link process) (RFU)
#MAP_DEF_LOCATION:= $(BUILD_FILES_PATH)/$(MAPPING_DEF_NAME)

#-------------------------------------------------------------------------------
# Result output files
#-------------------------------------------------------------------------------
# Binary file
BINARY_FILE     := $(BIN_PATH)/$(TRG_FILE_NAME).BIN

#-------------------------------------------------------------------------------
# Intermediate files
#-------------------------------------------------------------------------------
# MAP file location
INTER_MAP_FILE  := $(OBJ_PATH)/$(TRG_FILE_NAME).map
# AXF file location
INTER_AXF_FILE  := $(OBJ_PATH)/$(TRG_FILE_NAME).axf
# Compiler options file location
INTER_CC_OPTS   := $(OBJ_PATH)/cc.opt
# Assembler options file location
INTER_AS_OPTS   := $(OBJ_PATH)/as.opt
# Linker options file location
INTER_LD_OPTS   := $(OBJ_PATH)/ld.opt

#-------------------------------------------------------------------------------
# Specific compiler, linker, assembler options
#-------------------------------------------------------------------------------
# Specific compiler options
CC_SPEC_OPTS    := -O2 -Ospace  -D_ING_ARM_SDT_RELEASE
CC_SPEC_OPTS    +=  -D_EXPORT_ -D_EFT30_
CC_SPEC_OPTS    +=  -D__ISOZZSG__ -D__TELIUM__ -D_ING_APPLI_BINARY_NAME=\"BRI\" -D_ING_APPLI_FAMILY=\"BRI_204\" -D_ING_APPLI_TYPE=0x6e -D_ING_APPLI_CURRENT_CONFIG_NAME=\"ARM_SDT_RELEASE\" -D_ING_APPLI_FULL_BINARY_NAME=\"BRI.SGN\" -D_ING_APPLI_TELIUM1_FULL_BINARY_NAME=\"BRI.SGN\" -D_ING_APPLI_TELIUM2_FULL_BINARY_NAME=\"BRI.AGN\" -D_ING_APPLI_TELIUM_COMPATIBILITY=\"Telium_1\" -D_ING_APPLI_SIGN_MODE=\"Signed\" -D_ING_APPLI_CATALOG_FILE_EXTENSION=\"M3X\" -D_ING_APPLI_CURRENT_CONFIG_TOOLCHAIN_ROOT_LOCATION=\"${appli_current_config_toolchain_root_location}\" $(INCLUDES_PATH)
# Specific assembler options
AS_SPEC_OPTS    :=  $(INCLUDES_PATH)
# Specific linker options
LD_SPEC_OPTS    := 

#-------------------------------------------------------------------------------
# SRC_OBJS is the list of the project object files
#-------------------------------------------------------------------------------
SRC_OBJS        := \
$(OBJ_PATH)/trc.o \
$(OBJ_PATH)/tbx.o \
$(OBJ_PATH)/tlm.o \
$(OBJ_PATH)/tlmhmi.o \
$(OBJ_PATH)/tlmmem.o \
$(OBJ_PATH)/std.o \
$(OBJ_PATH)/fmt.o \
$(OBJ_PATH)/dba.o \
$(OBJ_PATH)/drv.o \
$(OBJ_PATH)/dlg.o \
$(OBJ_PATH)/Main.o \
$(OBJ_PATH)/sgm.o \
$(OBJ_PATH)/map.o \
$(OBJ_PATH)/dft.o \
$(OBJ_PATH)/rpt.o \
$(OBJ_PATH)/scr.o \
$(OBJ_PATH)/str.o \
$(OBJ_PATH)/hdl.o \
$(OBJ_PATH)/val.o \
$(OBJ_PATH)/adm.o \
$(OBJ_PATH)/emv.o \
$(OBJ_PATH)/function.o \
$(OBJ_PATH)/iso.o \
$(OBJ_PATH)/log.o \
$(OBJ_PATH)/onl.o \
$(OBJ_PATH)/pmt.o \
$(OBJ_PATH)/req.o \
$(OBJ_PATH)/rev.o \
$(OBJ_PATH)/rsp.o \
$(OBJ_PATH)/tle.o \
$(OBJ_PATH)/cmm.o \
$(OBJ_PATH)/tlmchn.o \
$(OBJ_PATH)/tlmcry.o \
$(OBJ_PATH)/tlmemv.o \
$(OBJ_PATH)/tcan0020.o \
$(OBJ_PATH)/BRI.o \
$(OBJ_PATH)/LineEncryption.o \
$(OBJ_PATH)/AES.o \
$(OBJ_PATH)/keyinject.o \
$(OBJ_PATH)/prepaid.o \
$(OBJ_PATH)/logon.o \
$(OBJ_PATH)/rsagen.o \
$(OBJ_PATH)/prsa.o \
$(OBJ_PATH)/bignum.o \
$(OBJ_PATH)/havege.o \
$(OBJ_PATH)/timing.o \

#-------------------------------------------------------------------------------
# Dependencies
#-------------------------------------------------------------------------------
DEPENDENCIES    := \
$(BUILD_FILES_PATH)/makefile.mk

#===============================================================================
# Rule to make the project
#===============================================================================
#-------------------------------------------------------------------------------
# Rule for the binary files generation
#-------------------------------------------------------------------------------
$(BINARY_FILE): $(INTER_AXF_FILE)
	$(FROM_ELF) -nodebug $< -bin $@ >nul
	@$(PRINTF) "'$@' binary file generated.\n"

#===============================================================================
# Rule for the link process
#===============================================================================
#-------------------------------------------------------------------------------
# Rule for the axf file generation
#-------------------------------------------------------------------------------
$(INTER_AXF_FILE): $(INTER_MAP_FILE) $(INTER_LD_OPTS) $(LIBS)
	@$(PRINTF) "'$@' link in progress...\n"
	$(LD) $(LD_SPEC_OPTS) -via $(INTER_LD_OPTS) -o $@ $(LIBS) >nul
	@$(RM) "elf"
	
#-------------------------------------------------------------------------------
# Rule for the map file generation
#-------------------------------------------------------------------------------
$(INTER_MAP_FILE): $(SRC_OBJS) $(INTER_LD_OPTS) $(LIBS)
	@$(CP) "D:\Program Files\Ingenico\IngeDev_7\plugins\com.ingenico.ingedev.telium.core_7.4.1.4\defaultSystemFiles\Obj\arm_sdt\$(STARTUP_OBJ_NAME)" "$(OBJ_PATH)"
	$(LD) $(LD_SPEC_OPTS) -via $(INTER_LD_OPTS) -list $@ $(LIBS) 

#===============================================================================
# Rule for the compilation process
#===============================================================================
ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/trc.d
endif
$(OBJ_PATH)/trc.o: D:/Documents\ and\ Settings/adr3an/IngeDev7_workspace/uta100407/sys/trc.c $(INTER_CC_OPTS) $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@$(PRINTF) "'D:/Documents and Settings/adr3an/IngeDev7_workspace/uta100407/sys/trc.c' compilation in progress...\n"
	$(CC) $(CC_SPEC_OPTS) -M "$<" -via $(INTER_CC_OPTS) > "$(basename $@).d"
	@$(GSAR) -s"\\" -r"/" "$(basename $@).d" >nul
	@$(GSAR) -s" " -r"\ " "$(basename $@).d" >nul
	@$(GSAR) -s"$(notdir $@)" -r"$@" "$(basename $@).d" >nul
	$(CC) $(CC_SPEC_OPTS) -o "$@" "$<" -via $(INTER_CC_OPTS)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/trc.o)
	@$(PRINTF) "done!\n"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/tbx.d
endif
$(OBJ_PATH)/tbx.o: D:/Documents\ and\ Settings/adr3an/IngeDev7_workspace/uta100407/sys/tbx.c $(INTER_CC_OPTS) $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@$(PRINTF) "'D:/Documents and Settings/adr3an/IngeDev7_workspace/uta100407/sys/tbx.c' compilation in progress...\n"
	$(CC) $(CC_SPEC_OPTS) -M "$<" -via $(INTER_CC_OPTS) > "$(basename $@).d"
	@$(GSAR) -s"\\" -r"/" "$(basename $@).d" >nul
	@$(GSAR) -s" " -r"\ " "$(basename $@).d" >nul
	@$(GSAR) -s"$(notdir $@)" -r"$@" "$(basename $@).d" >nul
	$(CC) $(CC_SPEC_OPTS) -o "$@" "$<" -via $(INTER_CC_OPTS)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/tbx.o)
	@$(PRINTF) "done!\n"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/tlm.d
endif
$(OBJ_PATH)/tlm.o: D:/Documents\ and\ Settings/adr3an/IngeDev7_workspace/uta100407/sys/tlm.c $(INTER_CC_OPTS) $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@$(PRINTF) "'D:/Documents and Settings/adr3an/IngeDev7_workspace/uta100407/sys/tlm.c' compilation in progress...\n"
	$(CC) $(CC_SPEC_OPTS) -M "$<" -via $(INTER_CC_OPTS) > "$(basename $@).d"
	@$(GSAR) -s"\\" -r"/" "$(basename $@).d" >nul
	@$(GSAR) -s" " -r"\ " "$(basename $@).d" >nul
	@$(GSAR) -s"$(notdir $@)" -r"$@" "$(basename $@).d" >nul
	$(CC) $(CC_SPEC_OPTS) -o "$@" "$<" -via $(INTER_CC_OPTS)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/tlm.o)
	@$(PRINTF) "done!\n"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/tlmhmi.d
endif
$(OBJ_PATH)/tlmhmi.o: D:/Documents\ and\ Settings/adr3an/IngeDev7_workspace/uta100407/sys/tlmhmi.c $(INTER_CC_OPTS) $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@$(PRINTF) "'D:/Documents and Settings/adr3an/IngeDev7_workspace/uta100407/sys/tlmhmi.c' compilation in progress...\n"
	$(CC) $(CC_SPEC_OPTS) -M "$<" -via $(INTER_CC_OPTS) > "$(basename $@).d"
	@$(GSAR) -s"\\" -r"/" "$(basename $@).d" >nul
	@$(GSAR) -s" " -r"\ " "$(basename $@).d" >nul
	@$(GSAR) -s"$(notdir $@)" -r"$@" "$(basename $@).d" >nul
	$(CC) $(CC_SPEC_OPTS) -o "$@" "$<" -via $(INTER_CC_OPTS)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/tlmhmi.o)
	@$(PRINTF) "done!\n"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/tlmmem.d
endif
$(OBJ_PATH)/tlmmem.o: D:/Documents\ and\ Settings/adr3an/IngeDev7_workspace/uta100407/sys/tlmmem.c $(INTER_CC_OPTS) $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@$(PRINTF) "'D:/Documents and Settings/adr3an/IngeDev7_workspace/uta100407/sys/tlmmem.c' compilation in progress...\n"
	$(CC) $(CC_SPEC_OPTS) -M "$<" -via $(INTER_CC_OPTS) > "$(basename $@).d"
	@$(GSAR) -s"\\" -r"/" "$(basename $@).d" >nul
	@$(GSAR) -s" " -r"\ " "$(basename $@).d" >nul
	@$(GSAR) -s"$(notdir $@)" -r"$@" "$(basename $@).d" >nul
	$(CC) $(CC_SPEC_OPTS) -o "$@" "$<" -via $(INTER_CC_OPTS)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/tlmmem.o)
	@$(PRINTF) "done!\n"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/std.d
endif
$(OBJ_PATH)/std.o: D:/Documents\ and\ Settings/adr3an/IngeDev7_workspace/uta100407/pri/std.c $(INTER_CC_OPTS) $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@$(PRINTF) "'D:/Documents and Settings/adr3an/IngeDev7_workspace/uta100407/pri/std.c' compilation in progress...\n"
	$(CC) $(CC_SPEC_OPTS) -M "$<" -via $(INTER_CC_OPTS) > "$(basename $@).d"
	@$(GSAR) -s"\\" -r"/" "$(basename $@).d" >nul
	@$(GSAR) -s" " -r"\ " "$(basename $@).d" >nul
	@$(GSAR) -s"$(notdir $@)" -r"$@" "$(basename $@).d" >nul
	$(CC) $(CC_SPEC_OPTS) -o "$@" "$<" -via $(INTER_CC_OPTS)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/std.o)
	@$(PRINTF) "done!\n"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/fmt.d
endif
$(OBJ_PATH)/fmt.o: D:/Documents\ and\ Settings/adr3an/IngeDev7_workspace/uta100407/pri/fmt.c $(INTER_CC_OPTS) $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@$(PRINTF) "'D:/Documents and Settings/adr3an/IngeDev7_workspace/uta100407/pri/fmt.c' compilation in progress...\n"
	$(CC) $(CC_SPEC_OPTS) -M "$<" -via $(INTER_CC_OPTS) > "$(basename $@).d"
	@$(GSAR) -s"\\" -r"/" "$(basename $@).d" >nul
	@$(GSAR) -s" " -r"\ " "$(basename $@).d" >nul
	@$(GSAR) -s"$(notdir $@)" -r"$@" "$(basename $@).d" >nul
	$(CC) $(CC_SPEC_OPTS) -o "$@" "$<" -via $(INTER_CC_OPTS)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/fmt.o)
	@$(PRINTF) "done!\n"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/dba.d
endif
$(OBJ_PATH)/dba.o: D:/Documents\ and\ Settings/adr3an/IngeDev7_workspace/uta100407/pri/dba.c $(INTER_CC_OPTS) $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@$(PRINTF) "'D:/Documents and Settings/adr3an/IngeDev7_workspace/uta100407/pri/dba.c' compilation in progress...\n"
	$(CC) $(CC_SPEC_OPTS) -M "$<" -via $(INTER_CC_OPTS) > "$(basename $@).d"
	@$(GSAR) -s"\\" -r"/" "$(basename $@).d" >nul
	@$(GSAR) -s" " -r"\ " "$(basename $@).d" >nul
	@$(GSAR) -s"$(notdir $@)" -r"$@" "$(basename $@).d" >nul
	$(CC) $(CC_SPEC_OPTS) -o "$@" "$<" -via $(INTER_CC_OPTS)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/dba.o)
	@$(PRINTF) "done!\n"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/drv.d
endif
$(OBJ_PATH)/drv.o: D:/Documents\ and\ Settings/adr3an/IngeDev7_workspace/uta100407/pri/drv.c $(INTER_CC_OPTS) $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@$(PRINTF) "'D:/Documents and Settings/adr3an/IngeDev7_workspace/uta100407/pri/drv.c' compilation in progress...\n"
	$(CC) $(CC_SPEC_OPTS) -M "$<" -via $(INTER_CC_OPTS) > "$(basename $@).d"
	@$(GSAR) -s"\\" -r"/" "$(basename $@).d" >nul
	@$(GSAR) -s" " -r"\ " "$(basename $@).d" >nul
	@$(GSAR) -s"$(notdir $@)" -r"$@" "$(basename $@).d" >nul
	$(CC) $(CC_SPEC_OPTS) -o "$@" "$<" -via $(INTER_CC_OPTS)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/drv.o)
	@$(PRINTF) "done!\n"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/dlg.d
endif
$(OBJ_PATH)/dlg.o: D:/Documents\ and\ Settings/adr3an/IngeDev7_workspace/uta100407/pri/dlg.c $(INTER_CC_OPTS) $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@$(PRINTF) "'D:/Documents and Settings/adr3an/IngeDev7_workspace/uta100407/pri/dlg.c' compilation in progress...\n"
	$(CC) $(CC_SPEC_OPTS) -M "$<" -via $(INTER_CC_OPTS) > "$(basename $@).d"
	@$(GSAR) -s"\\" -r"/" "$(basename $@).d" >nul
	@$(GSAR) -s" " -r"\ " "$(basename $@).d" >nul
	@$(GSAR) -s"$(notdir $@)" -r"$@" "$(basename $@).d" >nul
	$(CC) $(CC_SPEC_OPTS) -o "$@" "$<" -via $(INTER_CC_OPTS)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/dlg.o)
	@$(PRINTF) "done!\n"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/Main.d
endif
$(OBJ_PATH)/Main.o: uta/Main.c $(INTER_CC_OPTS) $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@$(PRINTF) "'uta/Main.c' compilation in progress...\n"
	$(CC) $(CC_SPEC_OPTS) -M "$<" -via $(INTER_CC_OPTS) > "$(basename $@).d"
	@$(GSAR) -s"\\" -r"/" "$(basename $@).d" >nul
	@$(GSAR) -s" " -r"\ " "$(basename $@).d" >nul
	@$(GSAR) -s"$(notdir $@)" -r"$@" "$(basename $@).d" >nul
	$(CC) $(CC_SPEC_OPTS) -o "$@" "$<" -via $(INTER_CC_OPTS)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/Main.o)
	@$(PRINTF) "done!\n"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/sgm.d
endif
$(OBJ_PATH)/sgm.o: uta/sgm.c $(INTER_CC_OPTS) $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@$(PRINTF) "'uta/sgm.c' compilation in progress...\n"
	$(CC) $(CC_SPEC_OPTS) -M "$<" -via $(INTER_CC_OPTS) > "$(basename $@).d"
	@$(GSAR) -s"\\" -r"/" "$(basename $@).d" >nul
	@$(GSAR) -s" " -r"\ " "$(basename $@).d" >nul
	@$(GSAR) -s"$(notdir $@)" -r"$@" "$(basename $@).d" >nul
	$(CC) $(CC_SPEC_OPTS) -o "$@" "$<" -via $(INTER_CC_OPTS)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/sgm.o)
	@$(PRINTF) "done!\n"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/map.d
endif
$(OBJ_PATH)/map.o: D:/Documents\ and\ Settings/adr3an/IngeDev7_workspace/ISOZZSG/str/map.c $(INTER_CC_OPTS) $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@$(PRINTF) "'D:/Documents and Settings/adr3an/IngeDev7_workspace/ISOZZSG/str/map.c' compilation in progress...\n"
	$(CC) $(CC_SPEC_OPTS) -M "$<" -via $(INTER_CC_OPTS) > "$(basename $@).d"
	@$(GSAR) -s"\\" -r"/" "$(basename $@).d" >nul
	@$(GSAR) -s" " -r"\ " "$(basename $@).d" >nul
	@$(GSAR) -s"$(notdir $@)" -r"$@" "$(basename $@).d" >nul
	$(CC) $(CC_SPEC_OPTS) -o "$@" "$<" -via $(INTER_CC_OPTS)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/map.o)
	@$(PRINTF) "done!\n"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/dft.d
endif
$(OBJ_PATH)/dft.o: D:/Documents\ and\ Settings/adr3an/IngeDev7_workspace/ISOZZSG/str/dft.c $(INTER_CC_OPTS) $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@$(PRINTF) "'D:/Documents and Settings/adr3an/IngeDev7_workspace/ISOZZSG/str/dft.c' compilation in progress...\n"
	$(CC) $(CC_SPEC_OPTS) -M "$<" -via $(INTER_CC_OPTS) > "$(basename $@).d"
	@$(GSAR) -s"\\" -r"/" "$(basename $@).d" >nul
	@$(GSAR) -s" " -r"\ " "$(basename $@).d" >nul
	@$(GSAR) -s"$(notdir $@)" -r"$@" "$(basename $@).d" >nul
	$(CC) $(CC_SPEC_OPTS) -o "$@" "$<" -via $(INTER_CC_OPTS)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/dft.o)
	@$(PRINTF) "done!\n"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/rpt.d
endif
$(OBJ_PATH)/rpt.o: D:/Documents\ and\ Settings/adr3an/IngeDev7_workspace/ISOZZSG/str/rpt.c $(INTER_CC_OPTS) $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@$(PRINTF) "'D:/Documents and Settings/adr3an/IngeDev7_workspace/ISOZZSG/str/rpt.c' compilation in progress...\n"
	$(CC) $(CC_SPEC_OPTS) -M "$<" -via $(INTER_CC_OPTS) > "$(basename $@).d"
	@$(GSAR) -s"\\" -r"/" "$(basename $@).d" >nul
	@$(GSAR) -s" " -r"\ " "$(basename $@).d" >nul
	@$(GSAR) -s"$(notdir $@)" -r"$@" "$(basename $@).d" >nul
	$(CC) $(CC_SPEC_OPTS) -o "$@" "$<" -via $(INTER_CC_OPTS)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/rpt.o)
	@$(PRINTF) "done!\n"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/scr.d
endif
$(OBJ_PATH)/scr.o: D:/Documents\ and\ Settings/adr3an/IngeDev7_workspace/ISOZZSG/str/scr.c $(INTER_CC_OPTS) $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@$(PRINTF) "'D:/Documents and Settings/adr3an/IngeDev7_workspace/ISOZZSG/str/scr.c' compilation in progress...\n"
	$(CC) $(CC_SPEC_OPTS) -M "$<" -via $(INTER_CC_OPTS) > "$(basename $@).d"
	@$(GSAR) -s"\\" -r"/" "$(basename $@).d" >nul
	@$(GSAR) -s" " -r"\ " "$(basename $@).d" >nul
	@$(GSAR) -s"$(notdir $@)" -r"$@" "$(basename $@).d" >nul
	$(CC) $(CC_SPEC_OPTS) -o "$@" "$<" -via $(INTER_CC_OPTS)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/scr.o)
	@$(PRINTF) "done!\n"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/str.d
endif
$(OBJ_PATH)/str.o: D:/Documents\ and\ Settings/adr3an/IngeDev7_workspace/ISOZZSG/str/str.c $(INTER_CC_OPTS) $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@$(PRINTF) "'D:/Documents and Settings/adr3an/IngeDev7_workspace/ISOZZSG/str/str.c' compilation in progress...\n"
	$(CC) $(CC_SPEC_OPTS) -M "$<" -via $(INTER_CC_OPTS) > "$(basename $@).d"
	@$(GSAR) -s"\\" -r"/" "$(basename $@).d" >nul
	@$(GSAR) -s" " -r"\ " "$(basename $@).d" >nul
	@$(GSAR) -s"$(notdir $@)" -r"$@" "$(basename $@).d" >nul
	$(CC) $(CC_SPEC_OPTS) -o "$@" "$<" -via $(INTER_CC_OPTS)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/str.o)
	@$(PRINTF) "done!\n"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/hdl.d
endif
$(OBJ_PATH)/hdl.o: D:/Documents\ and\ Settings/adr3an/IngeDev7_workspace/ISOZZSG/log/hdl.c $(INTER_CC_OPTS) $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@$(PRINTF) "'D:/Documents and Settings/adr3an/IngeDev7_workspace/ISOZZSG/log/hdl.c' compilation in progress...\n"
	$(CC) $(CC_SPEC_OPTS) -M "$<" -via $(INTER_CC_OPTS) > "$(basename $@).d"
	@$(GSAR) -s"\\" -r"/" "$(basename $@).d" >nul
	@$(GSAR) -s" " -r"\ " "$(basename $@).d" >nul
	@$(GSAR) -s"$(notdir $@)" -r"$@" "$(basename $@).d" >nul
	$(CC) $(CC_SPEC_OPTS) -o "$@" "$<" -via $(INTER_CC_OPTS)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/hdl.o)
	@$(PRINTF) "done!\n"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/val.d
endif
$(OBJ_PATH)/val.o: D:/Documents\ and\ Settings/adr3an/IngeDev7_workspace/ISOZZSG/log/val.c $(INTER_CC_OPTS) $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@$(PRINTF) "'D:/Documents and Settings/adr3an/IngeDev7_workspace/ISOZZSG/log/val.c' compilation in progress...\n"
	$(CC) $(CC_SPEC_OPTS) -M "$<" -via $(INTER_CC_OPTS) > "$(basename $@).d"
	@$(GSAR) -s"\\" -r"/" "$(basename $@).d" >nul
	@$(GSAR) -s" " -r"\ " "$(basename $@).d" >nul
	@$(GSAR) -s"$(notdir $@)" -r"$@" "$(basename $@).d" >nul
	$(CC) $(CC_SPEC_OPTS) -o "$@" "$<" -via $(INTER_CC_OPTS)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/val.o)
	@$(PRINTF) "done!\n"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/adm.d
endif
$(OBJ_PATH)/adm.o: D:/Documents\ and\ Settings/adr3an/IngeDev7_workspace/ISOZZSG/log/adm.c $(INTER_CC_OPTS) $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@$(PRINTF) "'D:/Documents and Settings/adr3an/IngeDev7_workspace/ISOZZSG/log/adm.c' compilation in progress...\n"
	$(CC) $(CC_SPEC_OPTS) -M "$<" -via $(INTER_CC_OPTS) > "$(basename $@).d"
	@$(GSAR) -s"\\" -r"/" "$(basename $@).d" >nul
	@$(GSAR) -s" " -r"\ " "$(basename $@).d" >nul
	@$(GSAR) -s"$(notdir $@)" -r"$@" "$(basename $@).d" >nul
	$(CC) $(CC_SPEC_OPTS) -o "$@" "$<" -via $(INTER_CC_OPTS)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/adm.o)
	@$(PRINTF) "done!\n"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/emv.d
endif
$(OBJ_PATH)/emv.o: D:/Documents\ and\ Settings/adr3an/IngeDev7_workspace/ISOZZSG/log/emv.c $(INTER_CC_OPTS) $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@$(PRINTF) "'D:/Documents and Settings/adr3an/IngeDev7_workspace/ISOZZSG/log/emv.c' compilation in progress...\n"
	$(CC) $(CC_SPEC_OPTS) -M "$<" -via $(INTER_CC_OPTS) > "$(basename $@).d"
	@$(GSAR) -s"\\" -r"/" "$(basename $@).d" >nul
	@$(GSAR) -s" " -r"\ " "$(basename $@).d" >nul
	@$(GSAR) -s"$(notdir $@)" -r"$@" "$(basename $@).d" >nul
	$(CC) $(CC_SPEC_OPTS) -o "$@" "$<" -via $(INTER_CC_OPTS)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/emv.o)
	@$(PRINTF) "done!\n"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/function.d
endif
$(OBJ_PATH)/function.o: D:/Documents\ and\ Settings/adr3an/IngeDev7_workspace/ISOZZSG/log/function.c $(INTER_CC_OPTS) $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@$(PRINTF) "'D:/Documents and Settings/adr3an/IngeDev7_workspace/ISOZZSG/log/function.c' compilation in progress...\n"
	$(CC) $(CC_SPEC_OPTS) -M "$<" -via $(INTER_CC_OPTS) > "$(basename $@).d"
	@$(GSAR) -s"\\" -r"/" "$(basename $@).d" >nul
	@$(GSAR) -s" " -r"\ " "$(basename $@).d" >nul
	@$(GSAR) -s"$(notdir $@)" -r"$@" "$(basename $@).d" >nul
	$(CC) $(CC_SPEC_OPTS) -o "$@" "$<" -via $(INTER_CC_OPTS)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/function.o)
	@$(PRINTF) "done!\n"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/iso.d
endif
$(OBJ_PATH)/iso.o: D:/Documents\ and\ Settings/adr3an/IngeDev7_workspace/ISOZZSG/log/iso.c $(INTER_CC_OPTS) $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@$(PRINTF) "'D:/Documents and Settings/adr3an/IngeDev7_workspace/ISOZZSG/log/iso.c' compilation in progress...\n"
	$(CC) $(CC_SPEC_OPTS) -M "$<" -via $(INTER_CC_OPTS) > "$(basename $@).d"
	@$(GSAR) -s"\\" -r"/" "$(basename $@).d" >nul
	@$(GSAR) -s" " -r"\ " "$(basename $@).d" >nul
	@$(GSAR) -s"$(notdir $@)" -r"$@" "$(basename $@).d" >nul
	$(CC) $(CC_SPEC_OPTS) -o "$@" "$<" -via $(INTER_CC_OPTS)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/iso.o)
	@$(PRINTF) "done!\n"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/log.d
endif
$(OBJ_PATH)/log.o: D:/Documents\ and\ Settings/adr3an/IngeDev7_workspace/ISOZZSG/log/log.c $(INTER_CC_OPTS) $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@$(PRINTF) "'D:/Documents and Settings/adr3an/IngeDev7_workspace/ISOZZSG/log/log.c' compilation in progress...\n"
	$(CC) $(CC_SPEC_OPTS) -M "$<" -via $(INTER_CC_OPTS) > "$(basename $@).d"
	@$(GSAR) -s"\\" -r"/" "$(basename $@).d" >nul
	@$(GSAR) -s" " -r"\ " "$(basename $@).d" >nul
	@$(GSAR) -s"$(notdir $@)" -r"$@" "$(basename $@).d" >nul
	$(CC) $(CC_SPEC_OPTS) -o "$@" "$<" -via $(INTER_CC_OPTS)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/log.o)
	@$(PRINTF) "done!\n"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/onl.d
endif
$(OBJ_PATH)/onl.o: D:/Documents\ and\ Settings/adr3an/IngeDev7_workspace/ISOZZSG/log/onl.c $(INTER_CC_OPTS) $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@$(PRINTF) "'D:/Documents and Settings/adr3an/IngeDev7_workspace/ISOZZSG/log/onl.c' compilation in progress...\n"
	$(CC) $(CC_SPEC_OPTS) -M "$<" -via $(INTER_CC_OPTS) > "$(basename $@).d"
	@$(GSAR) -s"\\" -r"/" "$(basename $@).d" >nul
	@$(GSAR) -s" " -r"\ " "$(basename $@).d" >nul
	@$(GSAR) -s"$(notdir $@)" -r"$@" "$(basename $@).d" >nul
	$(CC) $(CC_SPEC_OPTS) -o "$@" "$<" -via $(INTER_CC_OPTS)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/onl.o)
	@$(PRINTF) "done!\n"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/pmt.d
endif
$(OBJ_PATH)/pmt.o: D:/Documents\ and\ Settings/adr3an/IngeDev7_workspace/ISOZZSG/log/pmt.c $(INTER_CC_OPTS) $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@$(PRINTF) "'D:/Documents and Settings/adr3an/IngeDev7_workspace/ISOZZSG/log/pmt.c' compilation in progress...\n"
	$(CC) $(CC_SPEC_OPTS) -M "$<" -via $(INTER_CC_OPTS) > "$(basename $@).d"
	@$(GSAR) -s"\\" -r"/" "$(basename $@).d" >nul
	@$(GSAR) -s" " -r"\ " "$(basename $@).d" >nul
	@$(GSAR) -s"$(notdir $@)" -r"$@" "$(basename $@).d" >nul
	$(CC) $(CC_SPEC_OPTS) -o "$@" "$<" -via $(INTER_CC_OPTS)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/pmt.o)
	@$(PRINTF) "done!\n"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/req.d
endif
$(OBJ_PATH)/req.o: D:/Documents\ and\ Settings/adr3an/IngeDev7_workspace/ISOZZSG/log/req.c $(INTER_CC_OPTS) $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@$(PRINTF) "'D:/Documents and Settings/adr3an/IngeDev7_workspace/ISOZZSG/log/req.c' compilation in progress...\n"
	$(CC) $(CC_SPEC_OPTS) -M "$<" -via $(INTER_CC_OPTS) > "$(basename $@).d"
	@$(GSAR) -s"\\" -r"/" "$(basename $@).d" >nul
	@$(GSAR) -s" " -r"\ " "$(basename $@).d" >nul
	@$(GSAR) -s"$(notdir $@)" -r"$@" "$(basename $@).d" >nul
	$(CC) $(CC_SPEC_OPTS) -o "$@" "$<" -via $(INTER_CC_OPTS)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/req.o)
	@$(PRINTF) "done!\n"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/rev.d
endif
$(OBJ_PATH)/rev.o: D:/Documents\ and\ Settings/adr3an/IngeDev7_workspace/ISOZZSG/log/rev.c $(INTER_CC_OPTS) $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@$(PRINTF) "'D:/Documents and Settings/adr3an/IngeDev7_workspace/ISOZZSG/log/rev.c' compilation in progress...\n"
	$(CC) $(CC_SPEC_OPTS) -M "$<" -via $(INTER_CC_OPTS) > "$(basename $@).d"
	@$(GSAR) -s"\\" -r"/" "$(basename $@).d" >nul
	@$(GSAR) -s" " -r"\ " "$(basename $@).d" >nul
	@$(GSAR) -s"$(notdir $@)" -r"$@" "$(basename $@).d" >nul
	$(CC) $(CC_SPEC_OPTS) -o "$@" "$<" -via $(INTER_CC_OPTS)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/rev.o)
	@$(PRINTF) "done!\n"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/rsp.d
endif
$(OBJ_PATH)/rsp.o: D:/Documents\ and\ Settings/adr3an/IngeDev7_workspace/ISOZZSG/log/rsp.c $(INTER_CC_OPTS) $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@$(PRINTF) "'D:/Documents and Settings/adr3an/IngeDev7_workspace/ISOZZSG/log/rsp.c' compilation in progress...\n"
	$(CC) $(CC_SPEC_OPTS) -M "$<" -via $(INTER_CC_OPTS) > "$(basename $@).d"
	@$(GSAR) -s"\\" -r"/" "$(basename $@).d" >nul
	@$(GSAR) -s" " -r"\ " "$(basename $@).d" >nul
	@$(GSAR) -s"$(notdir $@)" -r"$@" "$(basename $@).d" >nul
	$(CC) $(CC_SPEC_OPTS) -o "$@" "$<" -via $(INTER_CC_OPTS)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/rsp.o)
	@$(PRINTF) "done!\n"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/tle.d
endif
$(OBJ_PATH)/tle.o: D:/Documents\ and\ Settings/adr3an/IngeDev7_workspace/ISOZZSG/log/tle.c $(INTER_CC_OPTS) $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@$(PRINTF) "'D:/Documents and Settings/adr3an/IngeDev7_workspace/ISOZZSG/log/tle.c' compilation in progress...\n"
	$(CC) $(CC_SPEC_OPTS) -M "$<" -via $(INTER_CC_OPTS) > "$(basename $@).d"
	@$(GSAR) -s"\\" -r"/" "$(basename $@).d" >nul
	@$(GSAR) -s" " -r"\ " "$(basename $@).d" >nul
	@$(GSAR) -s"$(notdir $@)" -r"$@" "$(basename $@).d" >nul
	$(CC) $(CC_SPEC_OPTS) -o "$@" "$<" -via $(INTER_CC_OPTS)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/tle.o)
	@$(PRINTF) "done!\n"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/cmm.d
endif
$(OBJ_PATH)/cmm.o: D:/Documents\ and\ Settings/adr3an/IngeDev7_workspace/uta100407/sys/cmm.c $(INTER_CC_OPTS) $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@$(PRINTF) "'D:/Documents and Settings/adr3an/IngeDev7_workspace/uta100407/sys/cmm.c' compilation in progress...\n"
	$(CC) $(CC_SPEC_OPTS) -M "$<" -via $(INTER_CC_OPTS) > "$(basename $@).d"
	@$(GSAR) -s"\\" -r"/" "$(basename $@).d" >nul
	@$(GSAR) -s" " -r"\ " "$(basename $@).d" >nul
	@$(GSAR) -s"$(notdir $@)" -r"$@" "$(basename $@).d" >nul
	$(CC) $(CC_SPEC_OPTS) -o "$@" "$<" -via $(INTER_CC_OPTS)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/cmm.o)
	@$(PRINTF) "done!\n"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/tlmchn.d
endif
$(OBJ_PATH)/tlmchn.o: D:/Documents\ and\ Settings/adr3an/IngeDev7_workspace/uta100407/sys/tlmchn.c $(INTER_CC_OPTS) $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@$(PRINTF) "'D:/Documents and Settings/adr3an/IngeDev7_workspace/uta100407/sys/tlmchn.c' compilation in progress...\n"
	$(CC) $(CC_SPEC_OPTS) -M "$<" -via $(INTER_CC_OPTS) > "$(basename $@).d"
	@$(GSAR) -s"\\" -r"/" "$(basename $@).d" >nul
	@$(GSAR) -s" " -r"\ " "$(basename $@).d" >nul
	@$(GSAR) -s"$(notdir $@)" -r"$@" "$(basename $@).d" >nul
	$(CC) $(CC_SPEC_OPTS) -o "$@" "$<" -via $(INTER_CC_OPTS)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/tlmchn.o)
	@$(PRINTF) "done!\n"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/tlmcry.d
endif
$(OBJ_PATH)/tlmcry.o: D:/Documents\ and\ Settings/adr3an/IngeDev7_workspace/uta100407/sys/tlmcry.c $(INTER_CC_OPTS) $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@$(PRINTF) "'D:/Documents and Settings/adr3an/IngeDev7_workspace/uta100407/sys/tlmcry.c' compilation in progress...\n"
	$(CC) $(CC_SPEC_OPTS) -M "$<" -via $(INTER_CC_OPTS) > "$(basename $@).d"
	@$(GSAR) -s"\\" -r"/" "$(basename $@).d" >nul
	@$(GSAR) -s" " -r"\ " "$(basename $@).d" >nul
	@$(GSAR) -s"$(notdir $@)" -r"$@" "$(basename $@).d" >nul
	$(CC) $(CC_SPEC_OPTS) -o "$@" "$<" -via $(INTER_CC_OPTS)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/tlmcry.o)
	@$(PRINTF) "done!\n"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/tlmemv.d
endif
$(OBJ_PATH)/tlmemv.o: D:/Documents\ and\ Settings/adr3an/IngeDev7_workspace/uta100407/sys/tlmemv.c $(INTER_CC_OPTS) $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@$(PRINTF) "'D:/Documents and Settings/adr3an/IngeDev7_workspace/uta100407/sys/tlmemv.c' compilation in progress...\n"
	$(CC) $(CC_SPEC_OPTS) -M "$<" -via $(INTER_CC_OPTS) > "$(basename $@).d"
	@$(GSAR) -s"\\" -r"/" "$(basename $@).d" >nul
	@$(GSAR) -s" " -r"\ " "$(basename $@).d" >nul
	@$(GSAR) -s"$(notdir $@)" -r"$@" "$(basename $@).d" >nul
	$(CC) $(CC_SPEC_OPTS) -o "$@" "$<" -via $(INTER_CC_OPTS)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/tlmemv.o)
	@$(PRINTF) "done!\n"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/tcan0020.d
endif
$(OBJ_PATH)/tcan0020.o: D:/Documents\ and\ Settings/adr3an/IngeDev7_workspace/uta100407/tst/an/tcan0020.c $(INTER_CC_OPTS) $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@$(PRINTF) "'D:/Documents and Settings/adr3an/IngeDev7_workspace/uta100407/tst/an/tcan0020.c' compilation in progress...\n"
	$(CC) $(CC_SPEC_OPTS) -M "$<" -via $(INTER_CC_OPTS) > "$(basename $@).d"
	@$(GSAR) -s"\\" -r"/" "$(basename $@).d" >nul
	@$(GSAR) -s" " -r"\ " "$(basename $@).d" >nul
	@$(GSAR) -s"$(notdir $@)" -r"$@" "$(basename $@).d" >nul
	$(CC) $(CC_SPEC_OPTS) -o "$@" "$<" -via $(INTER_CC_OPTS)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/tcan0020.o)
	@$(PRINTF) "done!\n"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/BRI.d
endif
$(OBJ_PATH)/BRI.o: D:/Documents\ and\ Settings/adr3an/IngeDev7_workspace/ISOZZSG/log/BRI.c $(INTER_CC_OPTS) $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@$(PRINTF) "'D:/Documents and Settings/adr3an/IngeDev7_workspace/ISOZZSG/log/BRI.c' compilation in progress...\n"
	$(CC) $(CC_SPEC_OPTS) -M "$<" -via $(INTER_CC_OPTS) > "$(basename $@).d"
	@$(GSAR) -s"\\" -r"/" "$(basename $@).d" >nul
	@$(GSAR) -s" " -r"\ " "$(basename $@).d" >nul
	@$(GSAR) -s"$(notdir $@)" -r"$@" "$(basename $@).d" >nul
	$(CC) $(CC_SPEC_OPTS) -o "$@" "$<" -via $(INTER_CC_OPTS)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/BRI.o)
	@$(PRINTF) "done!\n"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/LineEncryption.d
endif
$(OBJ_PATH)/LineEncryption.o: D:/Documents\ and\ Settings/adr3an/IngeDev7_workspace/ISOZZSG/log/LineEncryption.c $(INTER_CC_OPTS) $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@$(PRINTF) "'D:/Documents and Settings/adr3an/IngeDev7_workspace/ISOZZSG/log/LineEncryption.c' compilation in progress...\n"
	$(CC) $(CC_SPEC_OPTS) -M "$<" -via $(INTER_CC_OPTS) > "$(basename $@).d"
	@$(GSAR) -s"\\" -r"/" "$(basename $@).d" >nul
	@$(GSAR) -s" " -r"\ " "$(basename $@).d" >nul
	@$(GSAR) -s"$(notdir $@)" -r"$@" "$(basename $@).d" >nul
	$(CC) $(CC_SPEC_OPTS) -o "$@" "$<" -via $(INTER_CC_OPTS)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/LineEncryption.o)
	@$(PRINTF) "done!\n"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/AES.d
endif
$(OBJ_PATH)/AES.o: D:/Documents\ and\ Settings/adr3an/IngeDev7_workspace/ISOZZSG/log/AES.c $(INTER_CC_OPTS) $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@$(PRINTF) "'D:/Documents and Settings/adr3an/IngeDev7_workspace/ISOZZSG/log/AES.c' compilation in progress...\n"
	$(CC) $(CC_SPEC_OPTS) -M "$<" -via $(INTER_CC_OPTS) > "$(basename $@).d"
	@$(GSAR) -s"\\" -r"/" "$(basename $@).d" >nul
	@$(GSAR) -s" " -r"\ " "$(basename $@).d" >nul
	@$(GSAR) -s"$(notdir $@)" -r"$@" "$(basename $@).d" >nul
	$(CC) $(CC_SPEC_OPTS) -o "$@" "$<" -via $(INTER_CC_OPTS)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/AES.o)
	@$(PRINTF) "done!\n"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/keyinject.d
endif
$(OBJ_PATH)/keyinject.o: D:/Documents\ and\ Settings/adr3an/IngeDev7_workspace/ISOZZSG/log/keyinject.c $(INTER_CC_OPTS) $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@$(PRINTF) "'D:/Documents and Settings/adr3an/IngeDev7_workspace/ISOZZSG/log/keyinject.c' compilation in progress...\n"
	$(CC) $(CC_SPEC_OPTS) -M "$<" -via $(INTER_CC_OPTS) > "$(basename $@).d"
	@$(GSAR) -s"\\" -r"/" "$(basename $@).d" >nul
	@$(GSAR) -s" " -r"\ " "$(basename $@).d" >nul
	@$(GSAR) -s"$(notdir $@)" -r"$@" "$(basename $@).d" >nul
	$(CC) $(CC_SPEC_OPTS) -o "$@" "$<" -via $(INTER_CC_OPTS)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/keyinject.o)
	@$(PRINTF) "done!\n"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/prepaid.d
endif
$(OBJ_PATH)/prepaid.o: D:/Documents\ and\ Settings/adr3an/IngeDev7_workspace/ISOZZSG/log/prepaid.c $(INTER_CC_OPTS) $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@$(PRINTF) "'D:/Documents and Settings/adr3an/IngeDev7_workspace/ISOZZSG/log/prepaid.c' compilation in progress...\n"
	$(CC) $(CC_SPEC_OPTS) -M "$<" -via $(INTER_CC_OPTS) > "$(basename $@).d"
	@$(GSAR) -s"\\" -r"/" "$(basename $@).d" >nul
	@$(GSAR) -s" " -r"\ " "$(basename $@).d" >nul
	@$(GSAR) -s"$(notdir $@)" -r"$@" "$(basename $@).d" >nul
	$(CC) $(CC_SPEC_OPTS) -o "$@" "$<" -via $(INTER_CC_OPTS)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/prepaid.o)
	@$(PRINTF) "done!\n"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/logon.d
endif
$(OBJ_PATH)/logon.o: D:/Documents\ and\ Settings/adr3an/IngeDev7_workspace/ISOZZSG/log/logon.c $(INTER_CC_OPTS) $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@$(PRINTF) "'D:/Documents and Settings/adr3an/IngeDev7_workspace/ISOZZSG/log/logon.c' compilation in progress...\n"
	$(CC) $(CC_SPEC_OPTS) -M "$<" -via $(INTER_CC_OPTS) > "$(basename $@).d"
	@$(GSAR) -s"\\" -r"/" "$(basename $@).d" >nul
	@$(GSAR) -s" " -r"\ " "$(basename $@).d" >nul
	@$(GSAR) -s"$(notdir $@)" -r"$@" "$(basename $@).d" >nul
	$(CC) $(CC_SPEC_OPTS) -o "$@" "$<" -via $(INTER_CC_OPTS)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/logon.o)
	@$(PRINTF) "done!\n"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/rsagen.d
endif
$(OBJ_PATH)/rsagen.o: D:/Documents\ and\ Settings/adr3an/IngeDev7_workspace/ISOZZSG/log/rsagen.c $(INTER_CC_OPTS) $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@$(PRINTF) "'D:/Documents and Settings/adr3an/IngeDev7_workspace/ISOZZSG/log/rsagen.c' compilation in progress...\n"
	$(CC) $(CC_SPEC_OPTS) -M "$<" -via $(INTER_CC_OPTS) > "$(basename $@).d"
	@$(GSAR) -s"\\" -r"/" "$(basename $@).d" >nul
	@$(GSAR) -s" " -r"\ " "$(basename $@).d" >nul
	@$(GSAR) -s"$(notdir $@)" -r"$@" "$(basename $@).d" >nul
	$(CC) $(CC_SPEC_OPTS) -o "$@" "$<" -via $(INTER_CC_OPTS)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/rsagen.o)
	@$(PRINTF) "done!\n"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/prsa.d
endif
$(OBJ_PATH)/prsa.o: D:/Documents\ and\ Settings/adr3an/IngeDev7_workspace/ISOZZSG/log/prsa.c $(INTER_CC_OPTS) $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@$(PRINTF) "'D:/Documents and Settings/adr3an/IngeDev7_workspace/ISOZZSG/log/prsa.c' compilation in progress...\n"
	$(CC) $(CC_SPEC_OPTS) -M "$<" -via $(INTER_CC_OPTS) > "$(basename $@).d"
	@$(GSAR) -s"\\" -r"/" "$(basename $@).d" >nul
	@$(GSAR) -s" " -r"\ " "$(basename $@).d" >nul
	@$(GSAR) -s"$(notdir $@)" -r"$@" "$(basename $@).d" >nul
	$(CC) $(CC_SPEC_OPTS) -o "$@" "$<" -via $(INTER_CC_OPTS)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/prsa.o)
	@$(PRINTF) "done!\n"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/bignum.d
endif
$(OBJ_PATH)/bignum.o: D:/Documents\ and\ Settings/adr3an/IngeDev7_workspace/ISOZZSG/log/bignum.c $(INTER_CC_OPTS) $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@$(PRINTF) "'D:/Documents and Settings/adr3an/IngeDev7_workspace/ISOZZSG/log/bignum.c' compilation in progress...\n"
	$(CC) $(CC_SPEC_OPTS) -M "$<" -via $(INTER_CC_OPTS) > "$(basename $@).d"
	@$(GSAR) -s"\\" -r"/" "$(basename $@).d" >nul
	@$(GSAR) -s" " -r"\ " "$(basename $@).d" >nul
	@$(GSAR) -s"$(notdir $@)" -r"$@" "$(basename $@).d" >nul
	$(CC) $(CC_SPEC_OPTS) -o "$@" "$<" -via $(INTER_CC_OPTS)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/bignum.o)
	@$(PRINTF) "done!\n"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/havege.d
endif
$(OBJ_PATH)/havege.o: D:/Documents\ and\ Settings/adr3an/IngeDev7_workspace/ISOZZSG/log/havege.c $(INTER_CC_OPTS) $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@$(PRINTF) "'D:/Documents and Settings/adr3an/IngeDev7_workspace/ISOZZSG/log/havege.c' compilation in progress...\n"
	$(CC) $(CC_SPEC_OPTS) -M "$<" -via $(INTER_CC_OPTS) > "$(basename $@).d"
	@$(GSAR) -s"\\" -r"/" "$(basename $@).d" >nul
	@$(GSAR) -s" " -r"\ " "$(basename $@).d" >nul
	@$(GSAR) -s"$(notdir $@)" -r"$@" "$(basename $@).d" >nul
	$(CC) $(CC_SPEC_OPTS) -o "$@" "$<" -via $(INTER_CC_OPTS)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/havege.o)
	@$(PRINTF) "done!\n"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/timing.d
endif
$(OBJ_PATH)/timing.o: D:/Documents\ and\ Settings/adr3an/IngeDev7_workspace/ISOZZSG/log/timing.c $(INTER_CC_OPTS) $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@$(PRINTF) "'D:/Documents and Settings/adr3an/IngeDev7_workspace/ISOZZSG/log/timing.c' compilation in progress...\n"
	$(CC) $(CC_SPEC_OPTS) -M "$<" -via $(INTER_CC_OPTS) > "$(basename $@).d"
	@$(GSAR) -s"\\" -r"/" "$(basename $@).d" >nul
	@$(GSAR) -s" " -r"\ " "$(basename $@).d" >nul
	@$(GSAR) -s"$(notdir $@)" -r"$@" "$(basename $@).d" >nul
	$(CC) $(CC_SPEC_OPTS) -o "$@" "$<" -via $(INTER_CC_OPTS)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/timing.o)
	@$(PRINTF) "done!\n"
endif

#===============================================================================
# Rule for project name and configuration name display
#===============================================================================
.PHONY: displayInfo
displayInfo:
	@$(PRINTF) "                                     *-*-*\n"
	@$(PRINTF) "--- Project '$(PROJECT_NAME)', Configuration '$(CFG_NAME)' ---\n"

#===============================================================================
# Rule for output directories creation
#===============================================================================
.PHONY: createOutputDirs
createOutputDirs:
	@$(MKDIR) "$(OBJ_PATH)"
	@$(MKDIR) "$(BIN_PATH)"

#===============================================================================
# Rules for intermediate option files creation
#===============================================================================
$(INTER_CC_OPTS):
	$(PRINTF) "-c -g- -zas1 -apcs /interwork -Ecl\n" > $@

$(INTER_AS_OPTS):
	$(PRINTF) "-keep -g -fpu none\n" > $@

$(INTER_LD_OPTS):
	$(PRINTF) "-info totals,sizes -map -symbols $(INTER_MAP_FILE)\n" > $@
	$(PRINTF) "-ro-base 0x0 -rw-base 0x200000\n" >> $@
	$(PRINTF) "-first $(OBJ_PATH)/$(STARTUP_OBJ_NAME)(reset)\n" >> $@
	$(PRINTF) "$(OBJ_PATH)/$(STARTUP_OBJ_NAME)\n" >> $@
	@$(error ARM Linker error: cannot manage file with spaces in name (D:/Documents and Settings/adr3an/IngeDev7_workspace/uta100407/sys/trc.c))
	@$(error ARM Linker error: cannot manage file with spaces in name (D:/Documents and Settings/adr3an/IngeDev7_workspace/uta100407/sys/tbx.c))
	@$(error ARM Linker error: cannot manage file with spaces in name (D:/Documents and Settings/adr3an/IngeDev7_workspace/uta100407/sys/tlm.c))
	@$(error ARM Linker error: cannot manage file with spaces in name (D:/Documents and Settings/adr3an/IngeDev7_workspace/uta100407/sys/tlmhmi.c))
	@$(error ARM Linker error: cannot manage file with spaces in name (D:/Documents and Settings/adr3an/IngeDev7_workspace/uta100407/sys/tlmmem.c))
	@$(error ARM Linker error: cannot manage file with spaces in name (D:/Documents and Settings/adr3an/IngeDev7_workspace/uta100407/pri/std.c))
	@$(error ARM Linker error: cannot manage file with spaces in name (D:/Documents and Settings/adr3an/IngeDev7_workspace/uta100407/pri/fmt.c))
	@$(error ARM Linker error: cannot manage file with spaces in name (D:/Documents and Settings/adr3an/IngeDev7_workspace/uta100407/pri/dba.c))
	@$(error ARM Linker error: cannot manage file with spaces in name (D:/Documents and Settings/adr3an/IngeDev7_workspace/uta100407/pri/drv.c))
	@$(error ARM Linker error: cannot manage file with spaces in name (D:/Documents and Settings/adr3an/IngeDev7_workspace/uta100407/pri/dlg.c))
	@$(PRINTF) "$(OBJ_PATH)/Main.o\n" >> $@
	@$(PRINTF) "$(OBJ_PATH)/sgm.o\n" >> $@
	@$(error ARM Linker error: cannot manage file with spaces in name (D:/Documents and Settings/adr3an/IngeDev7_workspace/ISOZZSG/str/map.c))
	@$(error ARM Linker error: cannot manage file with spaces in name (D:/Documents and Settings/adr3an/IngeDev7_workspace/ISOZZSG/str/dft.c))
	@$(error ARM Linker error: cannot manage file with spaces in name (D:/Documents and Settings/adr3an/IngeDev7_workspace/ISOZZSG/str/rpt.c))
	@$(error ARM Linker error: cannot manage file with spaces in name (D:/Documents and Settings/adr3an/IngeDev7_workspace/ISOZZSG/str/scr.c))
	@$(error ARM Linker error: cannot manage file with spaces in name (D:/Documents and Settings/adr3an/IngeDev7_workspace/ISOZZSG/str/str.c))
	@$(error ARM Linker error: cannot manage file with spaces in name (D:/Documents and Settings/adr3an/IngeDev7_workspace/ISOZZSG/log/hdl.c))
	@$(error ARM Linker error: cannot manage file with spaces in name (D:/Documents and Settings/adr3an/IngeDev7_workspace/ISOZZSG/log/val.c))
	@$(error ARM Linker error: cannot manage file with spaces in name (D:/Documents and Settings/adr3an/IngeDev7_workspace/ISOZZSG/log/adm.c))
	@$(error ARM Linker error: cannot manage file with spaces in name (D:/Documents and Settings/adr3an/IngeDev7_workspace/ISOZZSG/log/emv.c))
	@$(error ARM Linker error: cannot manage file with spaces in name (D:/Documents and Settings/adr3an/IngeDev7_workspace/ISOZZSG/log/function.c))
	@$(error ARM Linker error: cannot manage file with spaces in name (D:/Documents and Settings/adr3an/IngeDev7_workspace/ISOZZSG/log/iso.c))
	@$(error ARM Linker error: cannot manage file with spaces in name (D:/Documents and Settings/adr3an/IngeDev7_workspace/ISOZZSG/log/log.c))
	@$(error ARM Linker error: cannot manage file with spaces in name (D:/Documents and Settings/adr3an/IngeDev7_workspace/ISOZZSG/log/onl.c))
	@$(error ARM Linker error: cannot manage file with spaces in name (D:/Documents and Settings/adr3an/IngeDev7_workspace/ISOZZSG/log/pmt.c))
	@$(error ARM Linker error: cannot manage file with spaces in name (D:/Documents and Settings/adr3an/IngeDev7_workspace/ISOZZSG/log/req.c))
	@$(error ARM Linker error: cannot manage file with spaces in name (D:/Documents and Settings/adr3an/IngeDev7_workspace/ISOZZSG/log/rev.c))
	@$(error ARM Linker error: cannot manage file with spaces in name (D:/Documents and Settings/adr3an/IngeDev7_workspace/ISOZZSG/log/rsp.c))
	@$(error ARM Linker error: cannot manage file with spaces in name (D:/Documents and Settings/adr3an/IngeDev7_workspace/ISOZZSG/log/tle.c))
	@$(error ARM Linker error: cannot manage file with spaces in name (D:/Documents and Settings/adr3an/IngeDev7_workspace/uta100407/sys/cmm.c))
	@$(error ARM Linker error: cannot manage file with spaces in name (D:/Documents and Settings/adr3an/IngeDev7_workspace/uta100407/sys/tlmchn.c))
	@$(error ARM Linker error: cannot manage file with spaces in name (D:/Documents and Settings/adr3an/IngeDev7_workspace/uta100407/sys/tlmcry.c))
	@$(error ARM Linker error: cannot manage file with spaces in name (D:/Documents and Settings/adr3an/IngeDev7_workspace/uta100407/sys/tlmemv.c))
	@$(error ARM Linker error: cannot manage file with spaces in name (D:/Documents and Settings/adr3an/IngeDev7_workspace/uta100407/tst/an/tcan0020.c))
	@$(error ARM Linker error: cannot manage file with spaces in name (D:/Documents and Settings/adr3an/IngeDev7_workspace/ISOZZSG/log/BRI.c))
	@$(error ARM Linker error: cannot manage file with spaces in name (D:/Documents and Settings/adr3an/IngeDev7_workspace/ISOZZSG/log/LineEncryption.c))
	@$(error ARM Linker error: cannot manage file with spaces in name (D:/Documents and Settings/adr3an/IngeDev7_workspace/ISOZZSG/log/AES.c))
	@$(error ARM Linker error: cannot manage file with spaces in name (D:/Documents and Settings/adr3an/IngeDev7_workspace/ISOZZSG/log/keyinject.c))
	@$(error ARM Linker error: cannot manage file with spaces in name (D:/Documents and Settings/adr3an/IngeDev7_workspace/ISOZZSG/log/prepaid.c))
	@$(error ARM Linker error: cannot manage file with spaces in name (D:/Documents and Settings/adr3an/IngeDev7_workspace/ISOZZSG/log/logon.c))
	@$(error ARM Linker error: cannot manage file with spaces in name (D:/Documents and Settings/adr3an/IngeDev7_workspace/ISOZZSG/log/rsagen.c))
	@$(error ARM Linker error: cannot manage file with spaces in name (D:/Documents and Settings/adr3an/IngeDev7_workspace/ISOZZSG/log/prsa.c))
	@$(error ARM Linker error: cannot manage file with spaces in name (D:/Documents and Settings/adr3an/IngeDev7_workspace/ISOZZSG/log/bignum.c))
	@$(error ARM Linker error: cannot manage file with spaces in name (D:/Documents and Settings/adr3an/IngeDev7_workspace/ISOZZSG/log/havege.c))
	@$(error ARM Linker error: cannot manage file with spaces in name (D:/Documents and Settings/adr3an/IngeDev7_workspace/ISOZZSG/log/timing.c))

#===============================================================================
# Make build rule
#===============================================================================
.PHONY: build
build: displayInfo createOutputDirs $(BINARY_FILE)
	@$(PRINTF) "done!\n"

#===============================================================================
# Make clean rule
#===============================================================================
.PHONY: clean
clean: displayInfo
	@$(PRINTF) "deleting intermediate files...\n"
	@$(RM) "$(BINARY_FILE)"
ifneq "$(wildcard $(OBJ_PATH)/*.*)" ""
	@$(RM) "$(OBJ_PATH)/*.*"
endif
	@$(PRINTF) "done!\n"
