/*******************************************************************************
 * AppMain.c
 *------------------------------------------------------------------------------
 * Application entry point.
 * This file was automatically generated by INGEDEV and must be filled out
 * by the developer.
 ******************************************************************************/
#ifdef __cplusplus
extern "C" {
#endif

#include <unicapt.h>
#include "message.h"


/* Application entry point */
void ApplicationMain(void)
{
   int16 ret;
   static amgMsg_t msgReceive;
   while(1)
   {
      amgSynchroMsgAdd(MSG_POWER_ON);
      ret = amgReceive(AMG_INFINITE, &msgReceive);
      if(ret == RET_OK)
      {
         treatRecMsg(&msgReceive);         
      }
      
   }
   psyTaskDelete();
}

#ifdef __cplusplus
}
#endif
